### ISSUE TITLE
ToDo's

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/attribute_contentarticle#1]
- [x] Remove the srcMetaModel/deprecated-autoload.php
- [x] Rename srcMetaModles to src
- [x] Rename srcContao to bridge or drive or anything what is better than srcContao 
- [x] Add missing gitignores
- [x] Add `.github` templates
- [x] Check naming "Add" vs. "clear" https://github.com/MetaModels/attribute_contentarticle/blob/9136ce80bc5a67a01eff39ee47b9178dc9c9ec68/srcMetaModel/EventListener/InitializeListener.php#L83-L112
- [x] Remove https://github.com/MetaModels/attribute_contentarticle/blob/5903b84f186e4cba004ca2e07aa8b1118a059588/srcMetaModel/EventListener/GetOptionsListener.php#L57
- [x] Remove https://github.com/MetaModels/attribute_contentarticle/blob/9136ce80bc5a67a01eff39ee47b9178dc9c9ec68/srcMetaModel/EventListener/InitializeListener.php#L26
- [x] Refactor Foo\Bar to \Foo\Bar::class https://github.com/MetaModels/attribute_contentarticle/blob/5903b84f186e4cba004ca2e07aa8b1118a059588/srcMetaModel/Resources/contao/config/config.php#L24-L23
- [x] Remove obsolete language directories (`fr`, `it`)
- [x] Move transifex related contents from `composer.json` to `ctb.json`
- [x] Remove unused method: https://github.com/MetaModels/attribute_contentarticle/blob/dc4d790b57946a863d912e0a32365342bf734d81/src/Attribute/ContentArticle.php#L75-L81
- [x] Refactor class: remove extend https://github.com/MetaModels/attribute_contentarticle/blob/5903b84f186e4cba004ca2e07aa8b1118a059588/srcMetaModel/Table/ArticleContent.php
- [x] Check all files in "root" to change or delete
- [x] Disable widget as long as the record has not yet been saved and show hint like "save item before you can create content elements"
- [x] Change to queryBuilder

**Open:**

- [x] Add unit tests

**Comment by zonky2** [comment]
@stefanheimes update to-do

**Comment by zonky2** [comment]
ready
